### ISSUE TITLE
mdl-select - contents are not scrollable

### ISSUE THREAD

**Issue by timeswind** [posva/vue-mdl#38]
how to set the select box a fix-height and make the options scrollable

**Comment by posva** [comment]
The component needs some specific update to handle this. Thanks for reporting it!

**Comment by posva** [comment]
I'll actually do it, no need to close 😉

**Comment by nickknissen** [comment]
What is the progress on this? Because if it's weeks away i'll properly create a pull request for this

**Comment by posva** [comment]
@nickknissen I had some issues when trying to setup this.
You can definitely give it a try. IMO this is more about documenting how to handle this with CSS but it has been a long time since I tried, so I may be wrong.

**Comment by nickknissen** [comment]
Completly forgot to return to this issue.
But it can be accomplished with CSS

```css
.mdl-menu__container {
  max-height: 200px;
  overflow-y: scroll !important;
  box-shadow: 0 2px 2px 0 rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.2),0 1px 5px 0 rgba(0,0,0,.12);
  border: 1px solid rgba(0,0,0,.12);
}
```
